const SET_PRODUCTS = 'SET_PRODUCTS';

const SET_IS_CART_OPEN = 'SET_IS_CART_OPEN';
const CART_LOADING = 'CART_LOADING';
const SET_CART = 'SET_CART';
const EMPTY_CART = 'EMPTY_CART';
const REFRESH_CART = 'REFRESH_CART';

const SET_CHECKOUT = 'SET_CHECKOUT';
const RESET_CHECKOUT = 'RESET_CHECKOUT';
const REFRESH_ORDER = 'REFRESH_ORDER';

const GENERATE_CHECKOUT_TKN = 'GENERATE_CHECKOUT_TKN';
const ISLOADING_SHIPPING_DETAILS = 'ISLOADING_SHIPPING_DETAILS';
const GET_SHIPPING_COUNTRIES = 'GET_SHIPPING_COUNTRIES';
const GET_SHIPPING_STATES = 'GET_SHIPPING_STATES';
const GET_SHIPPING_OPTIONS = 'GET_SHIPPING_OPTIONS';

export const ACTIONS = {
  SET_IS_CART_OPEN, SET_CART, SET_PRODUCTS, EMPTY_CART, SET_CHECKOUT, CART_LOADING, ISLOADING_SHIPPING_DETAILS,GET_SHIPPING_COUNTRIES, GET_SHIPPING_STATES, GET_SHIPPING_OPTIONS, GENERATE_CHECKOUT_TKN, RESET_CHECKOUT, REFRESH_CART, REFRESH_ORDER
};